image:
  file: .gitpod.Dockerfile

tasks:
  - name: Prepare Bazel
    before: "./scripts/gitpod-init.sh"
    init: bazel build //...

vscode:
  extensions:
    - golang.go@0.27.2 # Frequently updated on Open VSX
    - dbaeumer.vscode-eslint@2.1.8 # Not frequently updated on Open VSX
    - BazelBuild.vscode-bazel@0.4.1 # Frequently updated on VSX
    - scalameta.metals@1.10.9 # Frequently updated on VSX
    - matklad.rust-analyzer@0.2.735 # Frequently updated on VSX
    - Ionide.Ionide-fsharp@5.7.3 # Frequently updated on VSX
    - muhammad-sammy.csharp@1.23.15 # Frequently updated on VSX
    - zxh404.vscode-proto3@0.5.4 # Frequently updated on VSX

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
